### ISSUE TITLE
Where can I download dataset?

### ISSUE THREAD

**Issue by hyunseoki** [manwaarkhd/CEPHA29#2]
I visited http://vision.seecs.edu.pk/CEPHA29/ and there is no page for registration, data download
is that official web site for challenge?

**Comment by manwaarkhd** [comment]
@hyunseoki, the registration page will be up by Monday 19, December 2022. After registration, we will send the participants all the instructions to download the dataset via email. Sorry, for the inconvenience.

**Comment by tbluo** [comment]
@hyunseoki Hello, have you downloaded the data set?

**Comment by hyunseoki** [comment]
> @tbluo 

Yes, I received download link via email from the competition staff

**Comment by tbluo** [comment]
Hello, this competition is no longer available for registration. Could you please share this data set with me? Thank you very much!



---- Replied Message ----
| From | Hyunseok, ***@***.***> |
| Date | 05/20/2023 21:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [manwaarkhd/CEPHA29] Where can I download dataset? (Issue #2) |

Yes, I received download link via email from the competition staff
